name: DevTest
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  docker-rpi-build:
    runs-on: [self-hosted, Linux, ARM64, rpi]
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Install Pytest 
      run: pip3 install pytest 
    - name: Install Wget
      run: pip3 install wget
    - name: Install PIL
      run: pip3 install pillow
    - name: Download Binary Dependencies
      run: python3 download_dependencies.py
    - name: Build DeepStack RPI Version
      run: sudo docker build -t deepquestai/deepstack:rpi . -f Dockerfile.arm64-rpi
    - name: Test Scene
      run: |
        sudo docker run -d --name deepstack -e VISION-SCENE=True -p 80:5000 deepquestai/deepstack:cpu
        cd tests
        export TEST_DATA_DIR=$PWD"/test_data"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd scene
        python3 -m pytest
        sudo docker container rm -f deepstack
    - name: Clean DeepStack RPI Version
      run: sudo docker image rm -f deepquestai/deepstack:rpi
    