name: DevTest
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  docker-gpu-build:
    runs-on: [self-hosted, Linux, X64, gpu]
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Install Pytest 
      run: pip3 install pytest 
    - name: Install Wget
      run: pip3 install wget
    - name: Install PIL
      run: pip3 install pillow
    - name: Download Binary Dependencies
      run: python3 download_dependencies.py
    - name: Build DeepStack GPU Cuda 10 Version
      run: sudo docker build -t deepquestai/deepstack:gpu-cu100 . -f Dockerfile.gpu --build-arg tag=gpu-cuda100-2357972848
    - name: Clean DeepStack GPU Cuda 10 Version
      run: sudo docker rm -f deepquestai/deepstack:gpu-cu100
   
    